name: format

on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
  pull_request:
    paths:
      - '**.lua'

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Format with Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.3.0
          args: --check .
