name: test

on:
  push:
    branches:
      - main
    paths:
      - '**.lua'
  pull_request:
    paths:
      - '**.lua'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Run tests
        run: make test
